-- QMS Ticketkeypad Schema
-- Run this if you need to recreate tables fresh

CREATE DATABASE IF NOT EXISTS qms_ticketkeypad;
USE qms_ticketkeypad;

CREATE TABLE IF NOT EXISTS `employees` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `EMPID` varchar(45) DEFAULT NULL,
  `EMPNAME` varchar(45) DEFAULT NULL,
  `ACTIVE` char(1) DEFAULT NULL,
  `ROLE` varchar(45) DEFAULT NULL,
  `PWD` varchar(45) DEFAULT NULL,
  `CENTERID` char(3) DEFAULT NULL,
  `ADDRESS` varchar(50) DEFAULT NULL,
  `MOBILE` varchar(45) DEFAULT NULL,
  `EMAILID` varchar(45) DEFAULT NULL,
  `DEPARTMENT` varchar(45) DEFAULT NULL,
  `NATIONALITY` varchar(45) DEFAULT NULL,
  `GENDER` varchar(45) DEFAULT NULL,
  `EMPTYPE` varchar(45) DEFAULT NULL,
  `CENTERNAME` varchar(45) DEFAULT NULL,
  `CREATEDDATE` datetime DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `doctorservice` (
  `SERVICEID` int(11) NOT NULL AUTO_INCREMENT,
  `SERVICE_E` varchar(200) DEFAULT NULL,
  `SHORTNAME` varchar(20) DEFAULT NULL,
  `CATEGORYID` smallint(6) DEFAULT NULL,
  `ZONE` smallint(6) DEFAULT NULL,
  `ACTIVE` char(1) DEFAULT NULL,
  `CLINICID` varchar(3) DEFAULT NULL,
  `ROOMNAME` varchar(10) DEFAULT NULL,
  `MEDSOFT_ID` varchar(20) DEFAULT NULL,
  `MEDSOFT_NAME` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`SERVICEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `hispatientdetails` (
  `SLNO` int(11) NOT NULL AUTO_INCREMENT,
  `PatientName` varchar(45) DEFAULT NULL,
  `RegNo` varchar(45) DEFAULT NULL,
  `VisitNo` varchar(45) DEFAULT NULL,
  `VisitDate` datetime DEFAULT NULL,
  `DoctorId` varchar(45) DEFAULT NULL,
  `DoctorName` varchar(45) DEFAULT NULL,
  `Department` varchar(45) DEFAULT NULL,
  `ClinicId` char(3) DEFAULT NULL,
  `ClinicName` varchar(100) DEFAULT NULL,
  `TicketNumber` varchar(45) DEFAULT NULL,
  `TicketTime` datetime DEFAULT NULL,
  `Active` char(1) DEFAULT NULL,
  PRIMARY KEY (`SLNO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `callhistory` (
  `SLNO` int(11) NOT NULL AUTO_INCREMENT,
  `TICKETNUMBER` varchar(50) DEFAULT NULL,
  `COUNTERID` varchar(105) DEFAULT NULL,
  `TOKENDATE` datetime DEFAULT NULL,
  `SERVICEID` int(11) DEFAULT NULL,
  `STATUSSCREENDISPLAYALL` smallint(6) DEFAULT NULL,
  `STATUSCALLDISPLAYALL` smallint(6) DEFAULT NULL,
  `ZONE` varchar(6) DEFAULT NULL,
  `TYPE` char(1) DEFAULT NULL,
  `CENTERID` char(3) DEFAULT NULL,
  PRIMARY KEY (`SLNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `companydetails` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMPANYNAME` varchar(100) DEFAULT NULL,
  `COMPANYADDRESS` varchar(100) DEFAULT NULL,
  `COMPANYID` char(3) DEFAULT NULL,
  `ACTIVE` char(1) DEFAULT NULL,
  `LOGO` varchar(2000) DEFAULT NULL,
  `KIOSKMESSAGE1` varchar(250) DEFAULT NULL,
  `KIOSKMESSAGE2` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `category` (
  `CATEGORYID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORYE` varchar(45) DEFAULT NULL,
  `ACTIVE` char(1) DEFAULT NULL,
  `CENTERID` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CATEGORYID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `service` (
  `SERVICEID` int(11) NOT NULL AUTO_INCREMENT,
  `SERVICEEN` varchar(200) DEFAULT NULL,
  `SHORTNAMEEN` varchar(20) DEFAULT NULL,
  `ZONE` smallint(6) DEFAULT NULL,
  `ACTIVE` char(1) DEFAULT NULL,
  `CENTERID` char(3) DEFAULT NULL,
  `CATEGORYID` int(11) DEFAULT NULL,
  PRIMARY KEY (`SERVICEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `counter` (
  `COUNTERID` int(11) NOT NULL AUTO_INCREMENT,
  `COUNTERE` varchar(100) DEFAULT NULL,
  `TYPE` char(3) DEFAULT NULL,
  `ZONE` smallint(6) DEFAULT NULL,
  `ACTIVE` char(1) DEFAULT NULL,
  `CENTERID` char(3) DEFAULT NULL,
  PRIMARY KEY (`COUNTERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;